### ISSUE TITLE
can't see application 

### ISSUE THREAD

**Issue by rcemper** [jrpereirajr/iris-image-index-demo#1]
````
This link in README goes to nirvana:  Access the application. ==>  http://localhost:4200/    
nobody is listening at port 4200   
but during installation, I got this warning: Is this related ??

C:\GitHub\iris-image-index-demo\frontend>npx ng serve
Node.js version v10.15.1 detected.
The Angular CLI requires a minimum Node.js version of either v12.14 or v14.15.
````

**Comment by rcemper** [comment]
I did an upgrade of my node-js and it changed:
````
C:\GitHub\iris-image-index-demo\frontend>npx ng serve
An unhandled exception occurred: The 'buildOptimizer' option cannot be used without 'aot'.
See "C:\Users\cemper\AppData\Local\Temp\ng-7TpAeQ\angular-errors.log" for further details.
+++++++++++++++++++++++++++++
[error] Error: The 'buildOptimizer' option cannot be used without 'aot'.
    at generateWebpackConfig (C:\GitHub\iris-image-index-demo\frontend\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:22:15)
    at generateBrowserWebpackConfigFromContext (C:\GitHub\iris-image-index-demo\frontend\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:97:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.generateI18nBrowserWebpackConfigFromContext (C:\GitHub\iris-image-index-demo\frontend\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:47:20)
    at async setup (C:\GitHub\iris-image-index-demo\frontend\node_modules\@angular-devkit\build-angular\src\dev-server\index.js:92:47)
````
